const $=id=>document.getElementById(id),book=$('book'),bar=$('editor-bar'),typeButton=$('typography'),colorButton=$('color-menu'),themeButton=$('theme'),typePop=$('type-pop'),colorPop=$('color-pop');
const localColor=$('local-color'),documentColor=$('document-color'),localFamily=$('local-family'),docFamily=$('doc-family'),swatch=$('color-swatch');
let savedRange=null,localScale=1,theme='light',raf=null,ready=false;
const doc={size:20,family:'serif'},pair={dark:[51/255,58/255,54/255],light:[241/255,231/255,217/255],darkAlpha:1,lightAlpha:.96};
const family={inherit:'inherit',serif:'var(--font-serif)',sans:'var(--font-sans)',mono:'var(--font-mono)'};
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)),s2l=x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4,l2s=x=>x<=.0031308?12.92*x:1.055*Math.pow(Math.max(0,x),1/2.4)-.055;
function lab(rgb){let[r,g,b]=rgb.map(s2l),l=.4122214708*r+.5363325363*g+.0514459929*b,m=.2119034982*r+.6806995451*g+.1073969566*b,s=.0883024619*r+.2817188376*g+.6299787005*b,L=Math.cbrt(l),M=Math.cbrt(m),S=Math.cbrt(s);return[.2104542553*L+.793617785*M-.0040720468*S,1.9779984951*L-2.428592205*M+.4505937099*S,.0259040371*L+.7827717662*M-.808675766*S]}
function rgb(v){let[L,a,b]=v,l=(L+.3963377774*a+.2158037573*b)**3,m=(L-.1055613458*a-.0638541728*b)**3,s=(L-.0894841775*a-1.291485548*b)**3;return[4.0767416621*l-3.3077115913*m+.2309699292*s,-1.2684380046*l+2.6097574011*m-.3413193965*s,-.0041960863*l-.7034186147*m+1.707614701*s].map(l2s)}
const inGamut=x=>x.every(v=>v>=0&&v<=1);function gamut(v){let out=rgb(v);if(inGamut(out))return out;let lo=0,hi=1;for(let i=0;i<20;i++){let t=(lo+hi)/2,c=[v[0],v[1]*t,v[2]*t],r=rgb(c);if(inGamut(r)){lo=t;out=r}else hi=t}return out.map(x=>clamp(x))}
const h2r=h=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)].map(x=>x/255),r2h=x=>'#'+x.map(v=>Math.round(clamp(v)*255).toString(16).padStart(2,'0')).join(''),css=x=>`rgb(${x.map(v=>Math.round(clamp(v)*255)).join(' ')})`;
function luminance(x){let v=x.map(s2l);return .2126*v[0]+.7152*v[1]+.0722*v[2]}const contrast=(a,b)=>(Math.max(luminance(a),luminance(b))+.05)/(Math.min(luminance(a),luminance(b))+.05);
function safe(fg,bg,min=4.6){if(contrast(fg,bg)>=min)return fg;let L=lab(fg),dir=luminance(bg)>.45?-1:1;for(let i=0;i<=80;i++){let r=gamut([clamp(L[0]+dir*i/80),L[1],L[2]]);if(contrast(r,bg)>=min)return r}return luminance(bg)>.45?[0,0,0]:[1,1,1]}
const mix=(a,b,t)=>{let A=lab(a),B=lab(b);return gamut(A.map((x,i)=>x+(B[i]-x)*t))},composite=(x,a,b)=>x.map((v,i)=>v*a+b[i]*(1-a));
function endpoint(){return theme==='light'?{fg:pair.dark,bg:pair.light,back:[1,1,1],fa:pair.darkAlpha,ba:pair.lightAlpha}:{fg:pair.light,bg:pair.dark,back:[0,0,0],fa:pair.lightAlpha,ba:pair.darkAlpha}}
function target(){let e=endpoint(),bg=composite(e.bg,e.ba,e.back),fg=composite(e.fg,e.fa,bg);return{fg:safe(fg,bg),bg,back:e.back}}
let shown=target();function localColors(){document.querySelectorAll('[data-color-rel]').forEach(n=>{let d=n.dataset.colorRel.split(',').map(Number),b=lab(shown.fg),raw=gamut([b[0]+d[0],b[1]+d[1],b[2]+d[2]]);n.style.color=css(safe(raw,shown.bg))})}
function paint(p){shown=p;let r=document.documentElement,display=safe(mix(p.fg,p.bg,theme==='dark'?.12:.08),p.bg),muted=safe(mix(p.fg,p.bg,theme==='dark'?.34:.38),p.bg);r.style.setProperty('--ink',css(p.fg));r.style.setProperty('--surface',css(p.bg));r.style.setProperty('--backing',css(p.back));r.style.setProperty('--display-ink',css(display));r.style.setProperty('--toolbar-bg',`color-mix(in srgb,${css(p.bg)} 92%,transparent)`);r.style.setProperty('--rule',`color-mix(in srgb,${css(p.fg)} 17%,transparent)`);r.style.setProperty('--muted',css(muted));r.style.setProperty('--focus',css(safe(h2r('#4f766b'),p.bg,3)));r.style.colorScheme=theme;documentColor.value=r2h(endpoint().fg);swatch.style.background=css(endpoint().fg);localColors()}
function animate(mode='ease'){let end=target();if(matchMedia('(prefers-reduced-motion: reduce)').matches){paint(end);return}if(raf)cancelAnimationFrame(raf);let start={fg:[...shown.fg],bg:[...shown.bg],back:[...shown.back]},t0=performance.now(),dur=mode==='release'?720:600;function frame(now){let u=clamp((now-t0)/dur),e=mode==='release'?1-(1-u)**3:u<.5?2*u*u:1-(-2*u+2)**2/2,bg=mix(start.bg,end.bg,e),back=mix(start.back,end.back,e),fg=safe(mix(start.fg,end.fg,e),bg);paint({fg,bg,back});if(u<1)raf=requestAnimationFrame(frame);else raf=null}raf=requestAnimationFrame(frame)}
function translate(newFg){let e=endpoint(),A=lab(e.fg),B=lab(newFg),d=B.map((x,i)=>x-A[i]),other=gamut(lab(e.bg).map((x,i)=>x+d[i]));if(theme==='light'){pair.dark=newFg;pair.light=other}else{pair.light=newFg;pair.dark=other}}
function inside(r){return r&&book.contains(r.commonAncestorContainer)}function remember(){let s=getSelection();if(s&&s.rangeCount&&inside(s.getRangeAt(0))){savedRange=s.getRangeAt(0).cloneRange();sync()}}document.addEventListener('selectionchange',remember);function restore(){if(!savedRange)return false;let s=getSelection();s.removeAllRanges();s.addRange(savedRange);return true}function selected(){return savedRange&&!savedRange.collapsed&&inside(savedRange)}
function wrap(data={},style={}){if(!selected())return null;restore();let r=getSelection().getRangeAt(0),span=document.createElement('span');span.dataset.relStyle='true';Object.assign(span.dataset,data);Object.assign(span.style,style);try{r.surroundContents(span)}catch{span.append(r.extractContents());r.insertNode(span)}let nr=document.createRange();nr.selectNodeContents(span);let s=getSelection();s.removeAllRanges();s.addRange(nr);savedRange=nr.cloneRange();return span}
function exec(cmd,value=null){if(!selected())return;restore();document.execCommand(cmd,false,value);remember()}
function pops(except=null){for(let [b,p] of [[typeButton,typePop],[colorButton,colorPop]])if(p!==except){p.hidden=true;b.setAttribute('aria-expanded','false')}}function toggle(b,p){let open=p.hidden;pops(p);p.hidden=!open;b.setAttribute('aria-expanded',String(open));if(open){remember();p.querySelector('button,select,input')?.focus({preventScroll:true})}}
typeButton.onclick=()=>toggle(typeButton,typePop);colorButton.onclick=()=>toggle(colorButton,colorPop);document.addEventListener('pointerdown',e=>{if(!e.target.closest('#editor-bar,.tool-pop'))pops()});document.addEventListener('keydown',e=>{if(e.key==='Escape')pops()});bar.addEventListener('pointerdown',remember);[typePop,colorPop].forEach(p=>p.addEventListener('pointerdown',remember));
function sync(){let has=selected();['bold','italic','underline','link','local-minus','local-plus'].forEach(id=>$(id).disabled=!has);localColor.disabled=!has;localFamily.disabled=!has;$('local-size').textContent=Math.round(localScale*100)+'%';$('doc-size').textContent=Math.round(doc.size)+'px';docFamily.value=doc.family;documentColor.value=r2h(endpoint().fg);swatch.style.background=css(endpoint().fg)}
function localSize(f){if(!selected())return;localScale*=f;wrap({sizeRatio:String(f)},{fontSize:f+'em'});sync()}function docSize(f){doc.size=clamp(doc.size*f,11,56);document.documentElement.style.setProperty('--doc-size',doc.size+'px');sync()}
$('local-minus').onclick=()=>localSize(1/1.1);$('local-plus').onclick=()=>localSize(1.1);$('doc-minus').onclick=()=>docSize(1/1.1);$('doc-plus').onclick=()=>docSize(1.1);
localFamily.onchange=()=>{if(selected())wrap({familyRole:localFamily.value},{fontFamily:family[localFamily.value]})};docFamily.onchange=()=>{doc.family=docFamily.value;document.documentElement.style.setProperty('--doc-font',family[doc.family])};$('bold').onclick=()=>exec('bold');$('italic').onclick=()=>exec('italic');$('underline').onclick=()=>exec('underline');
localColor.oninput=()=>{if(!selected())return;let x=h2r(localColor.value),base=lab(shown.fg),pick=lab(x),d=pick.map((v,i)=>v-base[i]);wrap({colorRel:d.map(v=>v.toFixed(8)).join(',')},{color:css(safe(x,shown.bg))})};documentColor.oninput=()=>{translate(h2r(documentColor.value));animate('ease');sync()};documentColor.onchange=()=>animate('release');
themeButton.onclick=()=>{theme=theme==='light'?'dark':'light';themeButton.setAttribute('aria-label',theme==='light'?'Use dark presentation':'Use light presentation');animate('release');sync()};$('link').onclick=()=>{if(!selected())return;restore();let href=prompt('Link destination');if(href===null)return;href=href.trim();if(!href)return;try{let u=new URL(href,location.href);if(!['http:','https:'].includes(u.protocol)&&!href.startsWith('/'))return;exec('createLink',href)}catch{if(href.startsWith('/'))exec('createLink',href)}};
function readyEditor(){if(ready||book.getAttribute('aria-busy')!=='false')return;ready=true;book.contentEditable='true';book.spellcheck=true;book.setAttribute('role','textbox');book.setAttribute('aria-multiline','true');book.setAttribute('aria-label','Editable Huey reading copy');book.addEventListener('input',remember);sync();paint(target())}
new MutationObserver(readyEditor).observe(book,{attributes:true,attributeFilter:['aria-busy']});readyEditor();
let progressRaf=0;function progress(){progressRaf=0;let d=document.documentElement,max=Math.max(1,d.scrollHeight-innerHeight);d.style.setProperty('--progress',clamp(scrollY/max).toFixed(6))}addEventListener('scroll',()=>{if(!progressRaf)progressRaf=requestAnimationFrame(progress)},{passive:true});addEventListener('resize',progress);progress();
window.HueyEditor=Object.freeze({palette:()=>({theme,contrast:contrast(shown.fg,shown.bg)}),layout:()=>({toolbar:[...bar.querySelectorAll(':scope>button')].map(x=>x.id),rail:document.querySelectorAll('.chapter-index,.chapter-link').length,title:document.querySelectorAll('.reader-title:not([hidden])').length,paragraphs:document.querySelectorAll('.reader-paragraph').length}),selectText(text){let w=document.createTreeWalker(book,NodeFilter.SHOW_TEXT);while(w.nextNode()){let n=w.currentNode;if(n.parentElement?.closest('.paragraph-number'))continue;let i=n.nodeValue.indexOf(text);if(i>=0){let r=document.createRange();r.setStart(n,i);r.setEnd(n,i+text.length);let s=getSelection();s.removeAllRanges();s.addRange(r);savedRange=r.cloneRange();localScale=1;sync();return true}}return false},localSize,docSize,setDocumentColor(h){translate(h2r(h));paint(target());sync()},setLocalColor(h){if(!selected())return false;let x=h2r(h),b=lab(shown.fg),p=lab(x),d=p.map((v,i)=>v-b[i]);wrap({colorRel:d.map(v=>v.toFixed(8)).join(',')},{color:css(safe(x,shown.bg))});return true},toggleTheme(){theme=theme==='light'?'dark':'light';paint(target());sync()}});
